baseURL = "https://www.amisanasolutions.com/"
languageCode = "en-us"
title = "Amisana Solutions"
theme = "docsy"

[params]
  logo = "img/logo.png"

  [params.social]
    twitter = "https://twitter.com/yourhandle"
    linkedin = "https://linkedin.com/in/yourprofile"

  [[params.menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[params.menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[params.menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3

  [[params.menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
